[app]
    # Interface and port where the app will run its webserver.
    address = "0.0.0.0:9000"

# Database.
[db]
    host = "demo-db"
    port = 5432
    user = "tv"
    password = "tv"
    database = "listmonk"
    ssl_mode = "disable"
